config/routes.rb
Rails.application.routes.draw do
  get 'replays/index'

  get 'replays/new'

  get 'replays/create'

  get 'replays/destroy'

  resources :replays, only: [:index, :new, :create, :destroy]

  root 'welcome#index'
  get  'welcome/index'
  post 'auth/steam/callback' => 'welcome#auth_callback'
  get '/logout', to: 'welcome#logout'

  resources :matches do
    collection do
      get :status_update
      get :enter_slot
      get :clear_slot
    end
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/models/replay.rb
class Replay < ActiveRecord::Base
   #Tells rails to use this uploader for this model.
   mount_uploader :attachment, AttachmentUploader
   validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user
    if session[:current_user].present?
      session[:current_user]["uid"]
    else
      ""
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy,
    :status_update,
    :enter_slot,
    :clear_slot]

  def index
    @matches = Match.all
  end

  def show
  end

  def new
    @match = Match.new
    @match.owner = user

    respond_to do |format|
      if @match.save
        sync_new @match

        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if is_owner
      @match.destroy
      sync_destroy @match

      respond_to do |format|
        format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def enter_slot
    case params["slot"].to_i
      when 1
        @match.update_attribute(:player_1, user) unless @match.player_1.present?
      when 2
        @match.update_attribute(:player_2, user) unless @match.player_2.present?
      when 3
        @match.update_attribute(:player_3, user) unless @match.player_3.present?
      when 4
        @match.update_attribute(:player_4, user) unless @match.player_4.present?
      when 5
        @match.update_attribute(:player_5, user) unless @match.player_5.present?
      when 6
        @match.update_attribute(:player_6, user) unless @match.player_6.present?
      when 7
        @match.update_attribute(:player_7, user) unless @match.player_7.present?
      when 8
        @match.update_attribute(:player_8, user) unless @match.player_8.present?
      when 9
        @match.update_attribute(:player_9, user) unless @match.player_9.present?
      when 10
        @match.update_attribute(:player_10, user) unless @match.player_10.present?
      else
        return
    end
    sync_update @match

    render nothing: true
  end

  def clear_slot
    if is_owner
      case params["slot"].to_i
        when 1
          @match.update_attribute(:player_1, "")
        when 2
          @match.update_attribute(:player_2, "")
        when 3
          @match.update_attribute(:player_3, "")
        when 4
          @match.update_attribute(:player_4, "")
        when 5
          @match.update_attribute(:player_5, "")
        when 6
          @match.update_attribute(:player_6, "")
        when 7
          @match.update_attribute(:player_7, "")
        when 8
          @match.update_attribute(:player_8, "")
        when 9
          @match.update_attribute(:player_9, "")
        when 10
          @match.update_attribute(:player_10, "")
        else
          return
      end
    end
    sync_update @match

    render nothing: true
  end

  def is_owner
    if session[:current_user]["uid"] == @match.owner
      true
    else
      false
    end
  end

  def status_update
    if is_owner
      if @match.status == "Open"
        @match.update_attribute(:status, "Closed")
      elsif @match.status == "Closed"
        @match.update_attribute(:status, "Finished")
      else
        @match.update_attribute(:status, "Open")
      end

      sync_update @match
    end

    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:player_1, :player_2)
    end
end

app/controllers/replays_controller.rb
class ReplaysController < ApplicationController
   def index
      @replays = Replay.all
   end

   def new
      @replay = Replay.new
   end

   def create
      @replay = Replay.new(replay_params)

      if @replay.save
         redirect_to replays_path, notice: "The replay #{@replay.name} has been uploaded."
      else
         render "new"
      end

   end

   def destroy
      @replay = Replay.find(params[:id])
      @replay.destroy
      redirect_to replays_path, notice:  "The replay #{@replay.name} has been deleted."
   end

   private
      def replay_params
      params.require(:replay).permit(:name, :attachment)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :auth_callback

  def index; end

  def logout
    session[:current_user] = nil

    redirect_to :back
  end

  def auth_callback
    auth = request.env['omniauth.auth']
    session[:current_user] = { nick:  auth.info['nickname'],
                               image: auth.info['image'],
                               uid:   auth.uid }

    login_check(session[:current_user])

    redirect_to root_url
  end

  def login_check(steam_user)
    user = User.find_by(steam_id: steam_user["uid"])

    if user.present?
      user.update_attributes(nick: steam_user["nick"], imagem: steam_user["image"])
    else
      new_user = User.new
      new_user["steam_id"] = steam_user[:uid]
      new_user["nick"]     = steam_user[:nick]
      new_user["image"]    = steam_user[:image]
      new_user.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

  def match_status(status)
    if status == "Open"
      status = "Close"
    elsif status == "Closed"
      status = "Finish"
    else
      status = "Open"
    end
  end

end

app/helpers/replays_helper.rb
module ReplaysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchSync</title>
    <%= javascript_include_tag "https://js.pusher.com/3.0/pusher.min.js" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class = "container" style = "padding-top:20px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Owner</th>
      <th>Player 1</th>
      <th>Player 2</th>
      <th>Player ...</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <%= sync partial: 'index_match', resource: match %>
    <% end %>
    <%= sync_new partial: 'index_match', resource: Match.new %>
  </tbody>
</table>

<br>

<%= link_to 'Iniciar Partida', new_match_path %>

app/views/matches/show.html.erb
<%= sync partial: 'match', resource: @match %>

<div class="chat" style="background: whitesmoke;">
  <div id="tlkio" data-channel="dota2fortal-game<%= @match.id %>" style="width:100%;height:400px;"></div>
  <script async src="http://tlk.io/embed.js" type="text/javascript"></script>
</div>

<div class="upload">

</div>

<%= link_to "Voltar", matches_path %>

app/views/replays/create.html.erb
<h1>Replays#create</h1>
<p>Find me in app/views/replays/create.html.erb</p>

app/views/replays/destroy.html.erb
<h1>Replays#destroy</h1>
<p>Find me in app/views/replays/destroy.html.erb</p>

app/views/replays/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New replay", new_replay_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>

   <tbody>
      <% @replays.each do |replay| %>

         <tr>
            <td><%= replay.name %></td>
            <td><%= link_to "Download replay", replay.attachment_url %></td>
            <td><%= button_to "Delete",  replay, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{replay.name}?" %></td>
         </tr>

      <% end %>
   </tbody>

</table>

app/views/replays/new.html.erb
<% if !@replay.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @replay.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class = "well">
   <%= form_for @replay, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/sync/matches/_index_match.html.erb
<% if match.id != 1 %>
  <tr>
    <td><%= match.status %></td>
    <td><%= match.owner %></td>
    <td><%= match.player_1 %></td>
    <td><%= match.player_2 %></td>
    <% if match.status == "Open" %>
      <td><%= link_to 'Jogar', match %></td>
    <% end %>
    <td><%= link_to 'Deletar', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/sync/matches/_index_new_match.html.erb
<tr>
  <td><%= match.status %></td>
  <td><%= match.owner %></td>
  <td><%= match.player_1 %></td>
  <td><%= match.player_2 %></td>
  <% if match.status == "Open" %>
    <td><%= link_to 'Jogar', match %></td>
  <% end %>
  <td><%= link_to 'Deletar', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/sync/matches/_index_new_match_temp.html.erb
<tr>
  <td><%= match.status %></td>
  <td><%= match.owner %></td>
  <td><%= match.player_1 %></td>
  <td><%= match.player_2 %></td>
  <% if match.status == "Open" %>
    <td><%= link_to 'Jogar', match %></td>
  <% end %>
  <td><%= link_to 'Deletar', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/sync/matches/_match.html.erb
<div class="match">
  <p>
    <strong>Status:</strong>
    <%= @match.status %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= @match.owner %>
  </p>

  <div class="teams">
    <div class="team1" style="width:300px;">
      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 1), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 1), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

        <strong>Player 1:</strong>
        <%= @match.player_1 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 2), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 2), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>
        <strong>Player 2:</strong>
        <%= @match.player_2 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 3), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 3), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <strong>Player 3:</strong>
      <%= @match.player_3 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 4), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 4), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>
      <strong>Player 4:</strong>
      <%= @match.player_4 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 5), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>


      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 5), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <strong>Player 5:</strong>
      <%= @match.player_5 %>
      <hr>
    </div>

    <div class="team2" style="width:300px;">
      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 6), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>


      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 6), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <strong>Player 6:</strong>
      <%= @match.player_6 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 7), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>


      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 7), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <strong>Player 7:</strong>
      <%= @match.player_7 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 8), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 8), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <strong>Player 8:</strong>
      <%= @match.player_8 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 9), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 9), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <strong>Player 9:</strong>
      <%= @match.player_9 %>

      <hr>

      <%= button_to "x", clear_slot_matches_path(id: @match.id, slot: 10), remote: true,
          class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>

      <%= button_to "+", enter_slot_matches_path(id: @match.id, slot: 10), remote: true,
            class: "class", method: :get, data: { disable_with: "Wait..." }, style: "float: left;" %>
      <strong>Player 10:</strong>
      <%= @match.player_10 %>

      <hr>

      <strong>Game Status:</strong>
      <%= button_to match_status(@match.status), status_update_matches_path(id: @match.id),
      remote: true,class: "class", method: :get, data: { disable_with: "Wait..." } %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1> v0.1
<% if session.key? :current_user %>
  <h3>Current User:</h3>
  <%= image_tag session[:current_user]["image"] %>
  <p><%= session[:current_user]["nickname"] %></p>
  <p><%= session[:current_user]["uid"] %></p>

  <%= button_to "Logout", logout_path, method: :get,
    data: { disable_with: "Wait..." } %>

<% else %>
  <%= link_to image_tag("http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_large_noborder.png"), '/auth/steam' %>
<% end %>

<h1>Partidas:</h1>
<%= link_to "Lista de Partidas", matches_path %>